spring:
  application:
    name: book-my-show
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: 'jdbc:mysql://localhost:3306/bookmyshow'
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9000
